### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by cathylao** [LutingWang/HEAD#2]
Hi, thanks for the excellent work, I really appreciate the open source code. Since only the config of resnet18 is provided, could you please further provide the config file of Retina-MNV2?

**Comment by LutingWang** [comment]
You can modify the R18 version configs to MNV2, by adding the following config

```python
model = dict(
    backbone=dict(
        _delete_=True,
        type='MobileNetV2',
        act_cfg=dict(type='LeakyReLU', negative_slope=0.1),
        init_cfg=dict(
            type='Pretrained', checkpoint='open-mmlab://mmdet/mobilenet_v2',
        ),
    ),
    neck=dict(
        in_channels=[24, 32, 96, 1280],
    ),
)
```

Sorry for the incompleteness, since the code is still under refactor. More configs will be released shortly after. If you are eager, however, you may find the [`dev` branch](https://github.com/LutingWang/HEAD/tree/dev/configs/kd) helpful as a reference.

BTW, thanks for the attention. Please let me know of any further questions.

**Comment by LutingWang** [comment]
MNv2 RetinaNet has been supported. Please check it out.
